### ISSUE TITLE
[feat] arm64 `pkg` release?

### ISSUE THREAD

**Issue by Bun-Bun** [zwave-js/zwave-js-ui#2730]
Looking for a packaged release for arm64. 

Appears the builds here https://api.github.com/repos/zwave-js/zwave-js-ui/releases/latest are only x86_64?

**Comment by robertsLando** [comment]
Unfortunately this is not easy to do as github doesn't provide arm64 runners, and doing it in a docker container is complex. Do you need it for macOS or linux?

**Comment by Bun-Bun** [comment]
I did not know that. 

I am looking for linux, setting up on a rpi4 running alma linux 9.

**Comment by kpine** [comment]
@robertsLando I think if you add [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action) to your GitHub action you can build arm64 packages without issue. This action enables and configures QEMU binfmt so that non-native [targets](https://github.com/vercel/pkg#targets) can be generated by pkg. arm32 is a problem still, and I assume alpine is also (due to node serial build from source problem), but arm64 for Raspberry Pi-like platforms (e.g. Debian/Ubuntu) will work. I tested this locally (Intel workstation) and the resulting arm64 binary works fine on my Pi4. I'm using Debian 11, so I can't say how it fares for older versions.

I thought I'd also mention that the packaged version of node is [still at v14](https://github.com/zwave-js/zwave-js-ui/blob/30d020827084867fcc10746445862b8eacff3375/.github/workflows/release-it.yml#L19), compared to docker using [v18](https://github.com/zwave-js/zwave-js-ui/blob/30d020827084867fcc10746445862b8eacff3375/docker/Dockerfile#L57) now. I used v18 locally when generating the arm64 binary and it looks OK after a quick look.

**Comment by robertsLando** [comment]
> I think if you add [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action) to your GitHub action you can build arm64 packages without issue.

That's what I used to do, I just need to create another dedicated workflow and dockerfile for that

**Comment by kpine** [comment]
You don't need a new Dockerfile or workflow if all you want to do is build arm64 packages. Just add docker/setup-qemu-action as a step, then add the `linux-arm64` target to your package script. `pkg` figures out you've enabled QEMU binfmt and does an emulated build.

**Comment by robertsLando** [comment]
> Just add docker/setup-qemu-action as a step, then add the linux-arm64 target to your package script. pkg figures out you've enabled QEMU binfmt and does an emulated build.

Oh never tried that! I thought that setup-qemu was just for docker related stuff. So interesting, will give this a try soon

**Comment by Krakinou** [comment]
Hello,
Thanks for this wonderful tool!
Could you also add a release for armhf and armel as well? I'm using a Raspberry pi with debian and neither x86_64 nor arm64 can be run on it.

I don't know if this is easy or not, but I think that the whole set of architecture would be very useful : x86_64, x86, armhf, armel, and x86 would be useful.

**Comment by robertsLando** [comment]
@Krakinou Why not simply use docker?

**Comment by robertsLando** [comment]
@Krakinou I understand all the statements above but [pkg](https://github.com/vercel/pkg) builds are not so easy to do because them require native builds of some libs like serialport node and them are even more complex then docker when it comes to debug issues (I'm a maintainer of pkg and there are lot of bugs/weired things that could happen when using it).

If you never used docker I really suggest to give it a try as almost everything now uses it and it's not that complex (one commmand to run and one to upgrade). Docker becomes complex when you need to develop your own things, in that case you have to know it well. 

Another suggestion could be to use snap or build from source

**Comment by robertsLando** [comment]
Done, check: https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.6.1

**Comment by Krakinou** [comment]
I never noticed that you did it!
Thanks a lot
