### ISSUE TITLE
Simon IO 100 Roller Blind is not working as Roller Blind.

### ISSUE THREAD

**Issue by davidcalleja** [zwave-js/zwave-js-ui#3088]
### Version

Build/Run method:

[X] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[ ] Pkg

Z-Wave JS UI version: 8.16.6
Z-Wave JS version: 10.20.0

### Describe the bug

[After add a new device](https://github.com/zwave-js/node-zwave-js/pull/5743) (a Simon IO 100 Roller Blind) is not detecting as a roller blind because in Home Assistant section it says this: 

![Screenshot 2023-05-15 at 11 45 31](https://github.com/zwave-js/zwave-js-ui/assets/5727085/ef4b2936-ce57-4146-a2b5-5f1faba9cf91)

**Comment by robertsLando** [comment]
I misread the issue, I thought it was missing the node values of that device.

@davidcalleja Could you please tell me what controls you are missing from that device? Could you tell me what are the device valueId/command classes that you are missing in MQTT discovery? 

BTW If you are using home assistant I really suggest you to use zwave-js-integration that's the official way to work with zwave-js, in order to use it simply install that on home assistant and in zwave-js-ui enable WS Server in settings:

![2023-05-15_15-46](https://github.com/zwave-js/zwave-js-ui/assets/11502495/f23e1125-4575-48ed-bc99-ed5a3361868b)

**Comment by davidcalleja** [comment]
I am using Home Assistant but not directly, MQTT is the connector between because are not in same device.

This device is another "Simon IO 100 Roller Blind" with different ID. It must be same as this another roller blind I have because is same with different ID.

![Screenshot 2023-05-15 at 15 54 15](https://github.com/zwave-js/zwave-js-ui/assets/5727085/3a25319e-ab86-4049-80c6-3358d8bd2d7e)

**Comment by robertsLando** [comment]
Them are not the same device, one is 615-0-258 the other is 615-0-4, do you see command classes to control the cover position in node tab?

**Comment by robertsLando** [comment]
> I am using Home Assistant but not directly, MQTT is the connector between because are not in same device.

You can use the integration anyway, no need to have HA in the same device, just need HA to be able to point to the ip address to the device that is running Z-Wave JS UI. I really suggest you to give it a try

Anyway I should give a look at application logs, maybe the device is not recognized as a roller blind for some reason

**Comment by davidcalleja** [comment]
Yes but I'm using it not only with HA, I'm sending this events not others ;)

I don't know if I can help you with something because I am not expert with node :(

**Comment by davidcalleja** [comment]
Here you have both files with inclusion process done again.
 
[z-ui_2023-05-16.log](https://github.com/zwave-js/zwave-js-ui/files/11489526/z-ui_2023-05-16.log)
[zwavejs_2023-05-16.log](https://github.com/zwave-js/zwave-js-ui/files/11489527/zwavejs_2023-05-16.log)

**Comment by davidcalleja** [comment]
> What you mean with: "This are all you can see in node tab (nothing of this values works)" ? Aren't you able to set values from UI?

Yes I mean, if I click any switch or ser any value it do nothing.

If you like I can debug any branch before merge to master (run it in docker because I don't know how to debug it)

**Comment by AlCalzone** [comment]
@robertsLando that screenshot is showing the same issues with the value IDs I had recently when testing (missing fields, two buttons for things that should be just one, etc...). Maybe that's the actual issue? I think that's fixed now though.

The interview log looks fine.

**Comment by robertsLando** [comment]
@davidcalleja Could you check if you are using latest please? If you are using docker try with `master` tag. Also try to re-interview your device

**Comment by davidcalleja** [comment]
That log come from latest version. I have tried use `master`, `latest`, `8.16.1` and compile my own version with same results...

**Comment by davidcalleja** [comment]
I have done it and here you have files

[zwavejs_2023-05-17.log](https://github.com/zwave-js/zwave-js-ui/files/11499123/zwavejs_2023-05-17.log)
[z-ui_2023-05-17.log](https://github.com/zwave-js/zwave-js-ui/files/11499122/z-ui_2023-05-17.log)

**Comment by robertsLando** [comment]
>  we don't support overriding the device class. Not sure why the manufacturer turned this into a Multilevel Switch when its predecessors had a more fitting device class.

This could be a question to ask to the manufacturer maybe or what about using a compat flag for that? Asking because I think hass would have same problem since they use the same method to recognize devices types

**Comment by davidcalleja** [comment]
Something from my side? Or I just only have to wait because right know I can't use it on z-wave.

**Comment by AlCalzone** [comment]
> what about using a compat flag

I'm a bit hesitant since this will be one more piece of complexity to manage. Some device types come with mandatory supported CCs which aren't always advertised.

Is it not possible to manually change the MQTT discovery to say "this is a blind"?

I think if @davidcalleja were to use the recommended way of connecting the HA Z-Wave integration to Z-UI via a websocket, the solution would be clear - HA overrides the discovered device type for some devices:
https://github.com/home-assistant/core/blob/d16452bed7279cbcaaf0d2de74e0190ca132502e/homeassistant/components/zwave_js/discovery.py#L289-L296

**Comment by robertsLando** [comment]
Added an exception, try with `master` tag or wait for next release

**Comment by davidcalleja** [comment]
> Added an exception, try with `master` tag or wait for next release

With that solution, it works
