### ISSUE TITLE
Walli Controller association to Roller shutter 3

### ISSUE THREAD

**Issue by roblomq** [zwave-js/zwave-js-ui#3092]
I have a Fibaro Walli Controller (FGWCEU-201-1) and a Fibaro Roller Shutter (FGR-223) which I want to connect to each other.
According to the manuals,:
For the Roller Shutter parameter 151 is set to 1 (Roller Blind) and parameter 20 to 2 (Single momentary switch S1).
![2023-05-19_22h03_45](https://github.com/zwave-js/zwave-js-ui/assets/59142034/29e54815-2064-438a-8d99-5046f2516425)

For the Walli Controller parameter 20 is set on 5 (Roller Shutter controller Mode)
![2023-05-19_22h11_21](https://github.com/zwave-js/zwave-js-ui/assets/59142034/090898cd-532d-40e8-be1a-9e755133e133)

In zwavejs2mqtt I've created a group on the Walli Controller like below.
![2023-05-19_22h18_44](https://github.com/zwave-js/zwave-js-ui/assets/59142034/8dd95f3d-197c-4514-8f57-6135eab6ea52)

But for some reason nothing happens when I press the button. Maybe somebody can tell me what I do wrong?
What for me isn't clear (but assumed correct)

1. Is if the group function in zwavejs2mqtt is the so called association function (or is there a difference)?
2. Is it correct I have to create the association on the switch or do I have to set it on the roller shutter?
3. There is a "Endpoint" and "Target Endpoint", for the above there is only "Endpoint 0" is this correct?
4. For the group I can choose several options but I assume I have to use the "Multilevel" according the manual is this correct?

**Comment by robertsLando** [comment]
1. Yes
2. Yes, the association must be created on the device that have to send the command so in your case the switch
3. Endpoint is the instance of your device that you want to control, for example if your switch has 3 buttons it will have 3 endpoints each one represents a button so you have to choose that correctly, instance 0 is considered the root instance (the node itself). 
4. Yes I think so, I would need to see all available groups on switch BTW

It could be it's not working because you selected the wrong source/target endpoint
