### ISSUE TITLE
Unable to remove duplicate node.

### ISSUE THREAD

**Issue by hmjgriffon1** [zwave-js/zwave-js-ui#3182]
I added a ZCOMBO by First Alert (BRK Brands Inc) smoke detector with the QR code and it created 2 nodes. I try to remove the one them and it isn't working using remove under Failed Nodes, the node doesn't show up as failed though both copies are reporting in. Is there another way to remove it?

**Comment by robertsLando** [comment]
You should exclude it, manually reset the node and then call the remove/replace failed node against that node id

**Comment by hmjgriffon1** [comment]
yeah that might work, like to try to avoid that if possible since one of the copies is working fine and the beep makes my dog freak out, how long before a node gets marked dead if it doesn't send a heartbeat? I'm assuming the remove failed node will work then.

**Comment by robertsLando** [comment]
What happened to you can happen only when:

- You disconnect your node (unplug the power/battery)
- That node is marked as DEAD
- You call the remove failed node
- You try to include that node again


In this way when you plug your node again it start to communicate with the controller (he has no clue it has been removed because it was disconnected when you did it).

Generally the remove failed should be done only when: the device is broken, the device has been factory resetted.

For all other operations node should be excluded to avoid such kind of issues
