### ISSUE TITLE
Better Description for `Failed Nodes` in `Advanced` Menu

### ISSUE THREAD

**Issue by The00Dustin** [zwave-js/zwave-js-ui#3190]
**Is your feature request related to a problem? Please describe.**
Under `Failed Nodes`, the descriptive text currently reads:
> Manage nodes that are dead and/or marked as failed with the controller

While this text is certainly accurate when entering the `General Actions` menu via the `Advanced actions` button, I believe it should be changed on the `Advanced` menu for specific devices (which one enters by clicking or tapping the `ADVANCED` button).

I suggest this because while I now understand that this is where to remove a battery powered device even though it will say sleeping indefinitely (as opposed to dead or failed), there are many search results from people not understanding this, and that confusion may be easy to solve.

**Describe the solution you'd like**
If the text can be different between the menus, I suggest something like:
> Remove this failed node (if it is marked dead or sleeping)

for the individual device menu, with no change to the general actions menu.

**Describe alternatives you've considered**
My first draft was as follows:
> Remove nodes that are not working

However, that was before I realized the same description was used in two different places including one which would never remove a sleeping device.

**Additional context**
While it is speculation on my part, I believe this is what globe-earther was suggesting in https://github.com/zwave-js/zwave-js-ui/issues/2651

Note also that https://zwave-js.github.io/zwave-js-ui/#/usage/nodes-management mentions `Remove Failed Node` when discussing `Replace Failed Node`, but I couldn't find any prior information on the former.  While it is feasible that should be reported and addressed separately, this change could help with that deficit as well.

**Comment by AlCalzone** [comment]
Removing or replacing failed nodes will work on sleeping nodes too, this is correct. We need to be careful though not to indicate that this is meant to be used as the primary way to remove or replace sleeping nodes.

**Remove failed node** is only meant to remove devices that cannot be removed by excluding, because the device no longer exists or is truly dead (hardware failure), or the device was factory reset without the controller/Z-Wave JS noticing. This is true for both mains-powered and sleeping devices.

**Replace failed node** is meant to do the same thing, but by giving the node ID to another new device. This is sometimes "abused" by users who want to reuse the node IDs.

What contributes to the confusion IMO is the "check failed" function. We should probably just remove it from the UI. It simply checks if the device is marked as failed in the controller memory, but this isn't necessary for removal. Z-Wave JS will test if a device is reachable. Only if it isn't, the device can even be removed this way.
