### ISSUE TITLE
Cleanup device id display

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js-ui#3314]
**Is your feature request related to a problem? Please describe.**
The device ID labels are confusing because the decimal values are swapped compared to the hex values.

**Describe the solution you'd like**
Remove the decimal values and display only hex. Make the format same as Device DB.

**Describe alternatives you've considered**
N/A

**Additional context**

![image](https://github.com/zwave-js/zwave-js-ui/assets/791794/57227cfa-d436-486f-8227-384c69a5be05)

See the colored underlines. The order of the components in the decimal version are swapped compared to the hex version. I would just drop the decimal label, as it's not common to refer to devices to those. I'd keep the hex format, but maybe display as `0x0063:0x4944:0x3038` or `0x0063 0x4944:0x3038` since that's the format of the device DB.

**Comment by robertsLando** [comment]
> I'd keep the hex format, but maybe display as 0x0063:0x4944:0x3038 or 0x0063 0x4944:0x3038 since that's the format of the device DB.

I could do that, anyway this is a breaking change as the way I created devices ids has always been in that order and I use it in device values configurations and also for mqtt discovery configs. 

What I could do, in order to don't create breaking changes, is to just show it correctly in that place of the ui and keep it in the other order on the backend side. I don't like this solution so much BTW as it may cause confusion, there is a link to devices DB there anyway that let's you open the device configuration so there isn't a big problem related to that.

What do you think?

**Comment by robertsLando** [comment]
Fixed by https://github.com/zwave-js/zwave-js-ui/commit/fa5a8e941e359d0f890aa8aed66f0d2d49ca1d60
