### ISSUE TITLE
Cannot perform OTA updates from zwave-js-ui from packaged application

### ISSUE THREAD

**Issue by garbled1** [zwave-js/zwave-js-ui#3411]
Whenever I click on CHECK UPDATES or the OTA tab on a device, I get the following message:

Error while calling getAvailableFirmwareUpdates: Cannot check for firmware updates for node 11: Invalid host defined options (ZW0261)

I'm running 9.3.1 from zwave-js-ui-v9.3.1-linux.zip in the releases.  Is there something I'm supposed to configure to get this feature working?

**Comment by robertsLando** [comment]
I sincerly never saw such error. I need to ask @AlCalzone what that means

**Comment by AlCalzone** [comment]
@marcus-j-davies you had that in your dotnet wrapper, didn't you?

**Comment by marcus-j-davies** [comment]
Yup!

Its the `got` library I believe.
Running the driver  through `esbuild` resolves it for me, before using `pkg`

**Comment by john159753** [comment]
I am seeing the same on my standalone install (no docker, just the exe as a service with nssm on windows). You shouldn't need any special configuration or setup to get it working, It just worked for me previously.

**Comment by robertsLando** [comment]
@john159753 I agree with you but it's not that obvious, in order to package application I use a tool named pkg that does many things under the hoods that can create such issues that you don't see when running it without (like with docker, snap or nodejs).

This time the problem is related to the driver that starting from version 12 is using some ESM package that is not fully supported by pkg... I will try to see if I find a way to make it work... the alternative is to fix this on driver side someway like switching to a cjs version of `got` package like https://www.npmjs.com/package/got-cjs

**Comment by garbled1** [comment]
Should this be converted to a bug then?  I understand it might take you a bit to fix, but it's preventing me from doing fw updates on my nodes.  Thank you for all your effort though, it's appreciated!

**Comment by robertsLando** [comment]
@garbled1 Sure, done. A quick fix would be to simply try another deploy method like docker, snap or manually built.

**Comment by robertsLando** [comment]
@garbled1 Would the new [npm deploy](https://zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods?id=npm) method be an option for you?

**Comment by garbled1** [comment]
I can take a look.  My setup is a little complex, as I basically run it on a tiny VM, need to see how much needs to be installed to get npm running.  npm is at least a better option for me than docker.

How can I convert my settings from the binary version to that?  It seems to reference different files? (specifically the ZWAVEJS_EXTERNAL_CONFIG option)

**Comment by robertsLando** [comment]
> How can I convert my settings from the binary version to that? It seems to reference different files? (specifically the ZWAVEJS_EXTERNAL_CONFIG option)

Actually what you need to do is only to move everything you have in store directory to the new one or set as store path the store directory you are using now. Let's say you have your executable in folder `xxx/zui`, store folder should be `xxx/zui/store`, just set that as path in your pm2 config and you are done. In order to install npm you can use [nvm](https://github.com/nvm-sh/nvm#installing-and-updating)

**Comment by robertsLando** [comment]
@AlCalzone about this, could you switch to got-cjs?

**Comment by AlCalzone** [comment]
Shouldn't this also be solved by esbuild bundling like Marcus wrote?

**Comment by robertsLando** [comment]
Yeah that's the alternative, the only problem with that I would add another layer of "abstraction" to the pkg version

**Comment by robertsLando** [comment]
This should work in next version. In the meanwhile can anyone give a test to this? 

Linux x64:
https://wormhole.app/xaAYX#uFh7zJJTN0AKNWGGe-qHOw
