### ISSUE TITLE
Scene Activation CC (43) support with MQTT Discovery

### ISSUE THREAD

**Issue by barrydouu** [zwave-js/zwave-js-ui#3570]
### Version

Build/Run method:

[ X] Docker
[ ] Git Clone + npm install + npm run build + npm start
[ ] Pkg

Z-Wave JS UI version: 9.8.2
Z-Wave JS version: 12.4.3

### Describe the bug

I have a ZME_RC2  remote controller. It was working well until I upgrade to the last version (I don't know which version I was using before, one from the end of 2023), 
After troubleshooting, I ve found that the change states are not published to "right" mqtt topic.
In home assistant section, i see hass device json with command topic like : 
"command_topic": "zwave/27/112/0/10/set",

But when I check with mqtt explorer, when the device change, the value is set in "zwave/27/43/0/"

Here is debug information when I press a key on remote controller
```
2024-01-31 20:56:38.707 DEBUG MQTT: Publishing to zwave/27/lastActive: { time: 1706734598707, value: 1706734598706 } with options { qos: 1, retain: false }
2024-01-31 20:56:38.722 DEBUG MQTT: Publishing to zwave/27/43/0/sceneId: {
  time: 1706734598721,
  value: 72,
  nodeName: 'Telecommande',
  nodeLocation: ''
} with options { qos: 1, retain: false }
2024-01-31 20:56:38.724 INFO Z-WAVE: [Node 027] Value notification: 43-0-sceneId 72
2024-01-31 20:56:38.729 DEBUG MQTT: Publishing to zwave/27/43/0/dimmingDuration: {
  time: 1706734598726,
  value: Duration { unit: 'default', _value: 0, [value]: [Getter/Setter] },
  nodeName: 'Telecommande',
  nodeLocation: ''
} with options { qos: 1, retain: false }
2024-01-31 20:56:38.731 INFO Z-WAVE: [Node 027] Value updated: 43-0-dimmingDuration default => default
2024-01-31 20:56:38.959 DEBUG MQTT: Publishing to zwave/27/lastActive: { time: 1706734598959, value: 1706734598706 } with options { qos: 1, retain: false }
2024-01-31 20:56:39.724 DEBUG MQTT: Publishing to zwave/27/43/0/sceneId: {
  time: 1706734599724,
  value: undefined,
  nodeName: 'Telecommande',
  nodeLocation: ''
} with options { qos: 1, retain: false }
```

Here is the full Hass Device Json
```
{
  "type": "number",
  "object_id": "config_number_16",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "command_topic": "zwave/27/112/0/16/set",
    "enabled_by_default": false,
    "entity_category": "config",
    "min": 0,
    "max": 5,
    "state_topic": "zwave/27/112/0/16",
    "availability": [
      {
        "payload_available": "true",
        "payload_not_available": "false",
        "topic": "zwave/27/status",
        "value_template": "{{'true' if value_json.value else 'false'}}"
      },
      {
        "topic": "zwave/_CLIENTS/ZWAVE_GATEWAY-zwave-js-ui/status",
        "value_template": "{{'online' if value_json.value else 'offline'}}"
      },
      {
        "payload_available": "true",
        "payload_not_available": "false",
        "topic": "zwave/driver/status"
      }
    ],
    "availability_mode": "all",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc7bf3f61_node27"
      ],
      "manufacturer": "Z-Wave.Me",
      "model": "Z-Wave Remote Control+ (ZME_RC2)",
      "name": "Telecommande",
      "sw_version": "1.1"
    },
    "name": "Telecommande_config_number_16",
    "unique_id": "zwavejs2mqtt_0xc7bf3f61_27-112-0-16"
  },
  "discoveryTopic": "number/Telecommande/config_number_16/config",
  "values": [
    "112-0-16"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "number_config_number_16"
}
```

Tell me if I have to send other informations.

Thank you for your help

**Comment by robertsLando** [comment]
@barrydouu there is no support for `Scene Activation CC` (43) with MQTT discovery, I'm sorry. The `zwave/27/112/0/10/set` refers to a configuration value and that's not what you are looking for

**Comment by barrydouu** [comment]
So I just revert to 9.6.2
Hass Device Json is really different : 
`{
  "type": "sensor",
  "object_id": "scene_state_sceneid",
  "discovery_payload": {
    "state_topic": "zwave/27/43/0/sceneId",
    "value_template": "{{ value_json.value | default('') }}",
    "json_attributes_topic": "zwave/27/43/0/sceneId",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc7bf3f61_node27"
      ],
      "manufacturer": "Z-Wave.Me",
      "model": "Z-Wave Remote Control+ (ZME_RC2)",
      "name": "Telecommande",
      "sw_version": "1.1"
    },
    "name": "Telecommande_scene_state_sceneid",
    "unique_id": "zwavejs2mqtt_0xc7bf3f61_27-43-0-sceneId"
  },
  "discoveryTopic": "sensor/Telecommande/scene_state_sceneid/config",
  "values": [
    "43-0-sceneId"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_scene_state_sceneid"
}`

And the list of "subdevice" is different. With 9.6.2, I have only 4 
battery_level, battery_islow, scene_state_sceneid, scene_state_dimmingduration
With last version, I have a lot more. At least one for each "button" of the remote controller (ex : config_number_10, onfig_number_11, ...,  config_number_16)

Hope it could help

**Comment by robertsLando** [comment]
That PR has been from @ccutrer, I would be curious to know the reason why he removed that and added the state class, maybe he had a reason

**Comment by ccutrer** [comment]
For the Scene Activation CC, it's not that it was removed on purpose, it's that _writable_ values are no longer published (as read-only sensors!), since that doesn't make any sense. If I don't hear any different, I'll 

It seems to me that a writable-only value should be exposed as a [select](https://www.home-assistant.io/integrations/select.mqtt/) (without a state topic), a [number](https://www.home-assistant.io/integrations/number.mqtt/) (without a state topic), a series of [scenes](https://www.home-assistant.io/integrations/scene.mqtt/), or a series of [buttons](https://www.home-assistant.io/integrations/scene.mqtt/). WDYT @kpine? A read-write value should definitely be either a select or a number (perhaps based on some threshold?). If I don't hear any feedback in the next 48 hours, I'll just select one which seems to make the most sense based on the metadata my devices have, and do a PR.

As for setting the state class, and forcing it to be numeric... it's cause it _is_ numeric! The irony of the impact on Home Assistant is I had to fix some bugs in openHAB (and even for this particular case) where the value was missing in incoming JSON that Home Assistant just silently ignores, but openHAB was throwing an error on. Honestly, the Central Scene should not be sensors at all, though. They should be [device triggers](https://www.home-assistant.io/integrations/device_trigger.mqtt/), which can even map nicely to "single press", etc., which I'm pretty sure zwave-js already has all the metadata to do. I'll try and get a PR together to do this this weekend.

**Comment by barrydouu** [comment]
Hello

I just asked for this enhancement in domoticz too 
[ZWaveJSUI : Websocket integration instead of mqtt discovery](https://www.domoticz.com/forum/viewtopic.php?t=41959)

I'm not specialist enough to understand why one is better than the other one. 
I understand that websocket is easier than mqtt discovery. But in this case, mqtt was working before.

Should I hope the breaking change will be corrected or rollback ?

Thank you

**Comment by robertsLando** [comment]
> Should I hope the breaking change will be corrected or rollback ?

We are already working to fix the breaking change, see #3580

**Comment by robertsLando** [comment]
@barrydouu If you can add this link to your issue in the Domoticz forum: https://github.com/openhab/openhab-core/issues/4080

**Comment by barrydouu** [comment]
Done :) 

Thank you for the fixing work. I missed it.

**Comment by ccutrer** [comment]
(from @kpine)
> But you removed the `case` statement for Scene Activation CC, so it's no longer handled _at all_. Was that an accident?

It definitely was _not_ an accident. Before #3539, Scene Activation was exposed as a _read only_ `sensor`. But like you say at https://github.com/zwave-js/zwave-js-ui/pull/3580#discussion_r1477651685, `Scene Activation sceneId is always both readable and writable`, so it didn't work at all, at least for Home Assistant and openHAB (I can't speak to domoticz). Since that PR fixed Central Scene to not expose writable values as read-only sensors, there was no point in exposing Scene Activation at all. But Scene Activation CC is still a useful thing to expose, so this PR adds it (using a component type that makes it actually workable).

(from @kpine)
> I don't use MQTT so take my suggestions with a grain of salt.

Indeed, I am. But I'm also trying to get the lay of the land, and where different people are coming from. For example @robertsLando seems to be the primary maintainer of zwave-js-ui, and he also does not use MQTT (or at least MQTT Auto Discovery), and has no desire to maintain MQTT Auto Discovery, but seems to be open to others sending PRs to improve it for those that do. @kpine seems to be an infrequent contributor (at least PRs), but has a lot of opinions about MQTT AD, even though they don't use it.

(from @robertsLando)
> I completely agree and I would like to propose this to the OH team... 

Yes, this would be ideal. I can tell you that it's unlikely to happen anytime soon. I've become the maintainer in openHAB for the MQTT binding, and also Home Assistant Auto Discovery on top of that. Because it was not maintained at all. I don't have the time or the interest in writing an entire ZWave-JS binding from scratch using the websocket protocol. Part of that is that openHAB is Java, and while I've gotten fluent enough to be able to improve the existing bindings to fix lots of issues and add support for several things, it wouldn't exactly be quick for me to write an entire binding from scratch.  openHAB also already has a completely native ZWave binding, that's partially maintained, but mostly on life support. It has no support for S2 (though apparently someone is looking into adding it), let alone Smart Start, and general network management can be difficult. These are reasons I switched to ZWave-JS-UI in the first place.

(from @robertsLando)
> MQTT discovery is very complicated, limited and hard to maintain based on my experience. It is there just to give users an alternative but I would be very happy to completely remove it from the project in the future

This is certainly an opinion, though I would posit that that opinion comes from someone that doesn't actually use it. MQTT (and MQTT Auto Discovery) is the sole method that zigbee2mqtt uses to communicate with other projects, and it works just fine. ESPHome has a preference for a websocket (though speaking a Home Assistant native protocol, not a proprietary protocol, so is not an exact analogue to zwave-js-server), but maintains near-100% compatibility with MQTT Auto Discovery with zero issues. Tasmota has completely removed support for Home Assistant-based MQTT Auto Discovery in favor of their own proprietary (still MQTT based) auto discovery. I also maintain a number of other device-specific integrations that are set up similarly to ZWave-JS-UI (a separate process from the Home Automation server - i.e. Home Assistant, openHAB, or domoticz), and initially I used the [Homie Convention](https://homieiot.github.io) - mainly because I also thought Home Assistant MQTT Auto Discovery seemed unneccesarily complicated, and also lacking in actual _specification_ since it changes relatively often with no notice, simply based on the whims of Home Assistant itself. But then I had plenty of users that used Home Assistant, which does not support the Homie Convention, and I added support for Home Assistant MQTT Auto Discovery. Since then, the Homie convention has also proven itself to be somewhat capricious in changing its "specification," and given the popularity of Home Assistant, and other projects that support Home Assistant, I shifted my efforts on improving openHAB to better support Home Assistant Auto Discovery in order to have a larger bang-for-buck of how many 3rd party projects openHAB can work well with given my limited time.

Given all that, I'd be perfect happy to continue to improve support for MQTT Home Assistant Auto Discovery in zwave-js-ui, including taking Home Assistant itself as the baseline of compatibility (even though that's not a recommended configuration), ensuring it works well with openHAB, and taking into account the needs of domoticz users as well, as long as the latter two don't impose requirements that would "violate" how Home Assistant itself works with MQTT Auto Discovery. If you're not actually interested in that though, might I suggest that you set a firm deprecation/removal date or version for Home Assistant MQTT Auto Discovery in zwave-js-ui, and I'll instead focus my efforts on a 3rd party project that uses zwave-js-server to simply read metadata from zwave-js-ui, and then publish its own MQTT Home Assistant Auto Discovery metadata. I would do this in Ruby, my primary language, so I could develop it much faster. Especially since I already have a library that makes it easy to work with Home Assistant MQTT discovery, instead of manually throwing together the JSON.

**Comment by robertsLando** [comment]
@ccutrer Thanks for your detailed explaination.

> and has no desire to maintain MQTT Auto Discovery, but seems to be open to others sending PRs to improve it for those that do

I would better say that I prefer to focus in other issues/features giving that, based on our stats, the users using it are very few compared to the ones using the "official" ways. 

> This is certainly an opinion, though I would posit that that opinion comes from someone that doesn't actually use it.

I used it when I had introduced the support for it. I spawned an Home assistant instance and I started writing down all the things needed. First problem is that this feature has come after I added the mqtt gateway support and this is the first problem that makes it hard because the topic mapping have not been created with the discovery feature in mind, if you check thermostats for example they need a new discovery every time the mode changes, also each thermostat/fan or device that has more then a value lickely needs a custom device json in order to work propely. I also experienced many breaking changes in the past on each minor/major home assistant upgrade. Before the official Home Assistant Integration I had tons of discovery issues and I was just not able to sort them all alone.

All this is just to explain my points a bit better, anyway If you or any other user want to help me with that every help is more then welcome, thanks 🙏🏼

**Comment by ccutrer** [comment]
I get it!

> First problem is that this feature has come after I added the mqtt gateway support and this is the first problem that makes it hard because the topic mapping have not been created with the discovery feature in mind, if you check thermostats for example they need a new discovery every time the mode changes, also each thermostat/fan or device that has more then a value lickely needs a custom device json in order to work propely.

Two of my isolated integrations expose `climate` components to openHAB, and yeah, it was a bit of a contortion getting what I had originally designed for Homie discovery with very basic types to fit into the Home Assistant ecosystem where a `climate` component is a very complex object with many (possibly optional!) properties.

> I also experienced many breaking changes in the past on each minor/major home assistant upgrade.

I'm guessing you've experienced this more than I have. But yes, it can be quite annoying. Last summer in particular they had one that drastically changed how you should name devices and components. I've also seen references in openHAB's code to  discovery fields that no longer even exist in Home Assistant's docs; I'm still deciding what I do about them.

**Comment by barrydouu** [comment]
Hello

I've seen it was fixed in daily version (9.8.3). 
I've just updated, and tested and it's OK !

Thank you so much. My wife is happy. The remote control is for roller shutter. She can open and close without taking a computer :) 

I've seen lot of new HA Devices, like "number_config_number_XX", or "switch_config_switch_XX" and asking myself what is it ?

**Comment by ccutrer** [comment]
Those are to allow you to automate changing configuration option on your ZWave devices. As was mentioned above, they're "disabled by default". In Home Assistant, that means you have to go find them and explicitly enable them before you use them. In openHAB, it means they're hidden behind an "Advanced" check. It sounds like Domoticz does not respect that at all. Hopefully Domoticz exposes the name for those entities somewhere.

I use it for two things - first is my switches have status LEDs that are set via configuration params, and I automate turning on specific LEDs to specific colors depending on if a door is open, a window is open, etc. Second is I have some motion switches that can be set to manual, occupancy, or vacancy modes. I set them to occupancy during the day, and vacancy at night (meaning they won't turn _on_ when they see motion, but they'll turn off when there is no motion).

**Comment by akamming** [comment]
@robertsLando 
> MQTT discovery is very complicated, limited and hard to maintain based on my experience. It is there just to give users an alternative but I would be very happy to completely remove it from the project in the future

as a MQTT AD user let me state that i am very grateful that MQTT AD support is there. Currently MQTT AD is the only way to get zwave support in domoticz. So that's why i migrated to it.  And i was very happy to find out that in parallel i can now use my ZWAVE network from both Home Assistant and Domoticz in parallel.  So ofcourse I understand your point on maintenance, but i really hope the feature will be there for a long time..., cause it does add a lot af value to happy users like me

Keep up the good work!!

**Comment by akamming** [comment]
> You would be able to do exactly the same if Domoticz could add the support to websockets, anyway yeah no worries about MQTT AD, I know many are using it I just want to ensure users have the best experience using ZwaveJS

a ok.. tx a lot!

**Comment by gizmocuz** [comment]
> Those are to allow you to automate changing configuration option on your ZWave devices. As was mentioned above, they're "disabled by default". In Home Assistant, that means you have to go find them and explicitly enable them before you use them. In openHAB, it means they're hidden behind an "Advanced" check. It sounds like Domoticz does not respect that at all. Hopefully Domoticz exposes the name for those entities somewhere.
>
Yes, it seems Domoticz did ignore the 'disabled by default' flag for number devices.
For other types, they show up in the overall devices overview, where you also need to explicitly add them to the system.
I will make a patch for this....

Is there a reason to send these not-enabled-by-default values to MQTT?
Depending on the QoS this might have some impact on the system, especially when using bridges.
And I assume they are persistent as well. When any client connects (or application) it gets huge traffic for not-enabled items.

If you can set them to 'enabled' in the zwavejs-ui framework easily, I would prefer to send them just then.
