### ISSUE TITLE
ZW095 Aeon Labs Home Energy Meter - Gen 5 topics

### ISSUE THREAD

**Issue by gargamelonly** [zwave-js/zwave-js-ui#3577]
I have tried using the 3 phase "ZW095 Aeon Labs Home Energy Meter - Gen 5"
There are so many topics discovered, some are not easy to identify by name.
Also there is a missing command for resetting the accumulated values. 
It can be seen from https://github.com/zwave-js/zwave-js-ui/issues/232 image posted.

I am currently using OH Zwave binding and it is much more intuitive to identify the topics and configure parameters.
Is there a way to make this device configured parameters more friendly?

**Comment by apella12** [comment]
Also coming from OH so I'll interject some comments. First there is still an issue with the HA configs in OH regarding jinjava that are still being worked. You might run into OH log WARN messages until it is resolved. Second the HA configuration topics are new and there are some things being discussed to provide simplier options. Right no using zwave-js-ui 9.8 you can disable all of them and just enable the topics you are linking to OH items.  Configuration items are rarely changed, and you can use the Configuration table in zwave-js-ui instead of using a channel.  Lastly the meter reset is in the Meter section on zwave-js-ui for the node.  There is no channel, but possibly could be configured via custom code.

**Comment by robertsLando** [comment]
Thanks @apella12 for the help with OH/discovery issues 🙏🏼
