### ISSUE TITLE
Permanent restarts of driver after few seconds

### ISSUE THREAD

**Issue by Igitigit2** [zwave-js/zwave-js-ui#3593]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.8.3.3e632db

### ZwaveJS version

12.4.3

### Describe the bug

The program permanently restarts after few seconds while reinterviewing nodes. I reinstalled docker as well as z-wave js ui. My OS is the latest Buster version on a Raspberry Pi and I am using an older Z-Stick 5 and around 40 devices. A log is attached.
[zwavejs_2024-02-09.log](https://github.com/zwave-js/zwave-js-ui/files/14224289/zwavejs_2024-02-09.log)

### To Reproduce

Just starting the container

### Expected behavior

To see the GUI update all devices and not to restart every 30s or so.

**Comment by Igitigit2** [comment]
Wait, put this on hold, I just saw an other error message when I start the container without -d option and that error is listed on your docs!

**Comment by Igitigit2** [comment]
Ok, the script in your docs which is meant to fix issues with libseccomp2 doesn't work on Buster, since some public keys are missing. I am now upgrading to Bullseye...

**Comment by robertsLando** [comment]
Fixed?

**Comment by Igitigit2** [comment]
Yes! It was a lot of work and one device is still unresponsive, of course, a device which is not easily accessible, but the essential stuff works again (inc, mosquitto and Domoticz). It might be a good idea though to mention in your docs that the described  libseccomp2 error does not show up in the logs, but in the shell where you start zwavejs-ui and if you use docker, you need to start the container without the -d option...

**Comment by megamarco833** [comment]
hello i'll connect to this because also my brother has RPI2 + raZberry (so the ones connected to GPIO and not with USB dongles) and he is running zwave-JS with docker.
He has buster as RPI OS on his raspberry 2
He find that docker was always stopped and restarted
to fix the issue he updated the libseccomp2 following this guide:

[docker exec -i -t 123Solar-meterN nano /var/www/metern/config/config_daemon.php](https://github.com/sdr-enthusiasts/Buster-Docker-Fixes/tree/main)

after that the system is working very good.

**Comment by robertsLando** [comment]
@megamarco833 That's another issue mentioned here: https://github.com/zwave-js/zwave-js-ui/issues/3138
