### ISSUE TITLE
Driver not ready after each reboot

### ISSUE THREAD

**Issue by Epimedium** [zwave-js/zwave-js-ui#3722]
Hi,
I'm happily using the zwave-ui integration in my home assistant which is running on a NUC. 
The only problem I have is that after a reboot, because of power loss or a software updates, the usb dongle is not recognise anymore. Zwave-ui says "Driver not ready". After I unplug the dongle and the reconnect it after 20 seconds than it is properly recognised and everything starts working. 
HA core version:24.5.3
Supervisor:24.05.01
Dongle: AOTEC Z-stick gen 7 driver version 12.5.6

Is there a setting which can change this?

Best, E

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by Epimedium** [comment]
ok, very strange. We had a power outtage today and this issue occured. Only I didn't start the logging yet. When trying to recreate with the logging on, the problem didn't occur anymore.
I've tried several things like power off, reboot from HA, reboot proxmox VM. But none resulted in a disconnected zwave stick.
When it occurs again, I'll try and capture the moment. Thanks anyway!
Best, E

**Comment by larhedse** [comment]
> It's not uncommon for Z-Wave USB sticks to "lockup" after power outages. The solution is to pull and re-insert to do a hard reset. To avoid this problem you will want to put your Z-Wave host on a UPS battery backup.

Funny thing is, since I have this also, that I was recommended to change to Z-Wave JS UI to get rid of this kind of problem. But as written above, the problem exists no matter what...

**Comment by robertsLando** [comment]
Are you using latest ZUI version? If not try with it and if still not working try to disable soft-reset in settings

**Comment by AlCalzone** [comment]
> disable soft-reset

Does nothing for 700/800 series controllers. If anything, soft-reset could **help** in this situation, unless the controller is fully unresponsive due to the power outage.

This is an issue either on the OS or hardware level, so unfortunately nothing we can do about it.

**Comment by larhedse** [comment]
I'm running the latest from HAOS (v9.14.0 - there is a message inside Z-Wave JA UI that says latest is v9.14.1 - but it is not available from HAOS update service as far as I can tell) - and to be a bit more specific: I am on a RP4i 8GB with latest HAOS (12.4 - installed for 20h ago), now after the reboot only my sensors was available. I had to unplug/replug the USB Z-Wave Stick (it is a Z-Wave Me UZB1 - it has worked flawless on a Homeseer installation, so I can not see that the UZB1 is at fault here), just as I had in the included Z-Wave driver that comes with Home Assistant.

I would say there are three different ways a "reboot of any kind" will handle Z-Wave, and this is in possibility order (most likely in top):
1) Only Z-Wave Sensors seems to work...
2) No Z-Wave devices work...
3) If you are lucky, after a bunch of reboots (cold or hot), removed UZB1 USB stick and so fort: yes everything works...

There is less than 20% chance that the last one happens, so I have turned off auto update, on EVERYTHING  since any kind of restart seems to mess up the Z-Wave interface. If I go away on holiday, I have no idea if this systems is going to work or not...

**Comment by iMiMx** [comment]
Hardware: Aeontec Zwave Gen5 Plus (ZW090, firmware 1.2)
Debian Bookworm, Supervised install, modemmanager disabled
Powered USB 3.1 hub

Seeing similar to the post above - after a host reboot, sensors seem to work, plugs don't. Until:

- Stop Zwave JS
- Unplug the stick
- Wait 30 seconds / 1 minute
- Plug stick back in
- Start Zwave JS

... this usually then works.  Sometimes pinging the 'dead' devices works, but not always.

'Soft reset' has to be disabled for my stick, otherwise it doesn't even load the sensors.

Something that I have considered, I currently have the Zwave stick on a powered USB hub, I am/was wondering if I put it on an unpowered hub, or direct on a host port, whether it will then essentially power cycle with the host restart.

**Comment by AlCalzone** [comment]
Restarting the host might not power cycle the USB port. Power cycling the host may, depending on the port configuration.

**Comment by iMiMx** [comment]
Tried using '[hub-ctl](https://github.com/yy502/hub-ctrl)' to power off the USB port on the hub (which it does) - after stopping zwave js, waiting 1 minutes, then powering back on again - didn't seem to work/make any difference (I do see the disconnect and 'new usb device' in the logs).

Sadly, I think I'll have to stick to the manual process above ... and just make sure there are no reboots when not around!
