### ISSUE TITLE
Can not use camera (for scanning QR codes when doing inclusion)

### ISSUE THREAD

**Issue by larhedse** [zwave-js/zwave-js-ui#3769]
Strange thing: I can not use the Camera for scanning QR codes for S2 Inclusion into Z-Wave, on my Samsung Fold 3 or Samsung TAB S7 (both on Samsung UI 6.1 = absolute latest and greatest firmware for Android). Now I am new to using Z-Wave JS UI (with Home Assistant) however I expect the process to kind of straight forward, so it should not be an issue. Yes I do allow "Camera" in the app (both devices). However one thing I kind of expected was that is also should use storage?

Anyway, so when I could not scan with the "Camera" (no picture, and a button labeled "Retry" to no good - just nothing happens, no picture no nothing), I decided for a workaround: Take a picture and use the file input. Nope - that does not work either. I could select the file, but it could not process it. Could it be a storage security thing like the what I think above?

Anyway, there is no way for me to include a Fibaro S2 security product (since Fibaro seems to not like to print the 5-digit code on there products...).

So what am I doing wrong here? Why no camera?

**Comment by larhedse** [comment]
More info:

Above was with the Android App - So I thought I change to web browser, and well circumvent what ever.

No luck:
- Firefox on my Android Samsung Tab 7 - can not read the QR file, can not use the camera.
- Firefox on Windows 10 (MS Surface Book 2, yes a bit old but it works) - can not read the QR file, and can not find the camera. 

Now the camera on my Surface Book 2 works just fine, just like the camera on my mobile Samsung Fold 3, and the camera on my Samsung Tab 7.

From my perspective, it does not matter what kind of QR solution I try to use - they all fail. And it is not related to OS (tested Android and Win10), nor the Android app (Fold/TAB) or Firefox browser (Fold/TAB/Win10). I have also tested Chrome on my Win10 (MS Surface Book 2) - same story.

The QR Code inclusion does not work. Not over camera, not over file input.

**Comment by larhedse** [comment]
![QR code](https://github.com/zwave-js/zwave-js-ui/assets/8342357/98ea136b-af84-49a2-af1b-0a2d46a358c7)

This is the QR Code I have tested (I also, just in case and all that, have another QR code - both Fibaro units if it matters).

**Comment by cornellrwilliams** [comment]
1. In order to use the camera you need to have https setup. I believe in older versions of Z-Wave JS UI it would give you an error if you tried to scan a qr code without having https setup. I have it setup and it works great.
2. Smart Start and S2 Security are two separate things. This means your device can support S2 security but not smart start.
3. I don't think your device supports smart start. There are 3 things reason I believe this. 
- First your QR code is not a valid smart start QR Code. It should look like this. 
![smartstart1a](https://github.com/zwave-js/zwave-js-ui/assets/92619869/cf40b21b-0abc-48bb-a182-d77d34c150a9)
- Second when scanning the QR Code it should return a 52 character number that starts with 90. Once you have this 52 digit number you could then take that and input it into the text field on the smart start page. Scanning your QR Code returns an 9 digit code. 
- Lastly only 2 Fibaro products support smart start https://products.z-wavealliance.org/Search/DoAdvancedSearch?productName=&productIdentifier=&productDescription=&category=-1&brand=171&regionId=2&supportsS2=on&supportsSmartStart=on&order=.

**Comment by larhedse** [comment]
Right!

Thanks for your help - both of you, and since I am not going to change all my Fibaro stuff, there is just no reason to try to go to S2 security - it is simply put not supported (by Fibaro, which is of course very bad and typically Fibaro...) - and not to turn on SSL either (my Home Assistant is a "closed box system"). Why bother when it is not needed....

**Comment by larhedse** [comment]
No need for any more information.

Although I have to request that there is better error control for the camera - when SSL is not installed, it should say so, not just "Retry".

**Comment by robertsLando** [comment]
@larhedse most times ssl errors are just shown in chrome console but not accessible from js side, I should check if I'm able to reproduce this and fix

**Comment by robertsLando** [comment]
@mkitchingh could you tell me if you have any other web based application that is capable of decoding your QR codes? If it works with the app it doesn't matter as the app have access to more capabilities compared to the web apps. We also recently introduced a wasm based qr code detection that should perform much better with very small qr codes, did you tried using firefox instead?

**Comment by mkitchingh** [comment]
@robertsLando It looks like this may have been user error. I decided to try again today right before I saw this notification with your comment. I had never noticed I could reposition the screen and the focus square on the QR code using my finger.I noticed that by accident today, and it's actually worked Three out of three times. Maybe this was my fault.

**Comment by robertsLando** [comment]
@mkitchingh thanks for your feedback! Glad it works so :)
